stages:
- name: compile
  steps:
  - runScriptConfig:
      image: node:10.15.3
      shellScript: |-
        npm install --registry=https://registry.npm.taobao.org
        npm run build
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: frontend:v1.0
      pushRemote: true
      registry: 127.0.0.1:34713
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
