// =============================评分功能===================================
export const SET_MENU_STATUS = 'SET_MENU_STATUS';
export const HIDDEN_MODAL = 'HIDDEN_MODAL';
export const SHOW_MODAL = 'SHOW_MODAL';
export const SET_TEMPLATE = 'SET_TEMPLATE';
export const SET_MENU = 'SET_MENU';
export const SET_APPRAISAL_TEMPLATETYPE_STATUS = 'SET_APPRAISAL_TEMPLATETYPE_STATUS';
export const SET_GROUP_TITLE = 'SET_GROUP_TITLE';
export const SET_DATA_SOURCE = 'SET_DATA_SOURCE';
export const SET_PERSON_TITLE = 'SET_PERSON_TITLE';
export const SET_UNCOMPLETED_TEMPLATE = 'SET_UNCOMPLETED_TEMPLATE';
export const SET_CURRENT_GROUP = 'SET_CURRENT_GROUP';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_JUDGED_PEOPLE = 'SET_JUDGED_PEOPLE';
export const SET_KPI_DETAIL = 'SET_KPI_DETAIL';
export const SET_KPI_TITLE = 'SET_KPI_TITLE';
export const SET_TEMPLATE_TYPE = 'SET_TEMPLATE_TYPE';

// =============================配置功能===================================
export const SET_MAIN_PROCESS = 'SET_MAIN_PROCESS';
export const SET_USER_LIST = 'SET_USER_LIST';
export const SET_DEP_LIST = 'SET_DEP_LIST';
export const SET_SUB_PROCESS = 'SET_SUB_PROCESS';
export const SET_EDITABLE_TABLEHEADER = 'SET_EDITABLE_TABLEHEADER';
export const INIT_TEMPLATE_TYPE = 'INIT_TEMPLATE_TYPE';
export const SET_CURRENT_MBLX = 'SET_CURRENT_MBLX';
export const SET_CURRENT_MBLXID = 'SET_CURRENT_MBLXID';
export const SET_FAXX_STATUS = 'SET_FAXX_STATUS';
export const SET_PROGRAM_LIST = 'SET_PROGRAM_LIST';
export const SET_CURRENT_FAID = 'SET_CURRENT_FAID';
export const SET_TEMPLATE_LIST = 'SET_TEMPLATE_LIST';
export const SET_CURRENT_MBLXMC = 'SET_CURRENT_MBLXMC';
export const SET_CURRENT_TEMPLATE = 'SET_CURRENT_TEMPLATE';
export const SHOW_ADD_TEMPLATE = 'SHOW_ADD_TEMPLATE';
export const HIDDEN_ADD_TEMPLATE = 'HIDDEN_ADD_TEMPLATE';
export const SHOW_EDIT_TEMPLATE = 'SHOW_EDIT_TEMPLATE';
export const HIDDEN_EDIT_TEMPLATE = 'HIDDEN_EDIT_TEMPLATE';
export const SHOW_CREATE_TEMPLATE = 'SHOW_CREATE_TEMPLATE';
export const HIDDEN_CREATE_TEMPLATE = 'HIDDEN_CREATE_TEMPLATE';
export const SET_CURRENT_PWZID = 'SET_CURRENT_PWZID';
export const SET_JUDGE_LIST = 'SET_JUDGE_LIST';
export const SHOW_JUDGE_LIST = 'SHOW_JUDGE_LIST';
export const HIDDEN_JUDGE_LIST = 'HIDDEN_JUDGE_LIST';
export const SET_PROGRAM_STATUS = 'SET_PROGRAM_STATUS';
export const SET_TEMPLATETYPE_STATUS = 'SET_TEMPLATETYPE_STATUS';
export const SET_CONFIG_TEMPLATE_STATUS = 'SET_CONFIG_TEMPLATE_STATUS';
export const SET_JUDGE_TEAM = 'SET_JUDGE_TEAM';
export const SHOW_JUDGE_TEAMLIST = 'SHOW_JUDGE_TEAMLIST';
export const HIDDEN_JUDGE_TEAMLIST = 'HIDDEN_JUDGE_TEAMLIST';
export const RESET_JUDGETESM_LIST = 'RESET_JUDGETESM_LIST';
export const SET_ALL_JUDGELIST = 'SET_ALL_JUDGELIST';

// ========================== xiaomei and xiyu add on 2019/12/16 ====================
export const SET_MATCH_PROCESS = 'SET_MATCH_PROCESS';
export const SET_PROGRAME_LIST='SET_PROGRAME_LIST';
export const SET_DEP_BIND_PROGRAM = 'SET_DEP_BIND_PROGRAM';
export const SET_OBJECT_BIND_PROGRAM = 'SET_OBJECT_BIND_PROGRAM ';
export const SET_BIND_PROGRAM = 'SET_BIND_PROGRAM';

export const SET_TMPTYPE_LIST='SET_TMPTYPE_LIST';
export const BIND_TMPTYPE='BIND_TMPTYPE';
export const BIND_TEMPLATE_TYPE ='BIND_TEMPLATE_TYPE';
export const SET_TEMPLATE_COFIG = 'SET_TEMPLATE_COFIG';
export const SET_RESULT = 'SET_RESULT';
export const SET_SUB_MATCH = 'SET_SUB_MATCH';
export const SET_NULL = 'SET_NULL';

export const SET_OBJECT_STATUS = 'SET_OBJECT_STATUS';
export const SET_OBJECT_LIST = 'SET_OBJECT_LIST';
export const SET_ALLUSER_LIST = 'SET_ALLUSER_LIST';
export const SET_ALLDEP_LIST = 'SET_ALLDEP_LIST';